language: elixir
sudo: false
elixir:
  - 1.0.5
  - 1.1.0
 otp_release:
  - 17.4
  - 18.1
cache:
  directories:
    - _build
    - deps
after_success:
  - "mix compile && mix coveralls.travis"
after_script:
  - "MIX_ENV=docs mix deps.get"
  - "MIX_ENV=docs mix inch.report"

